version: "3"
services:
  api:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - DATABASE_URL=mongodb://admin:password123@db:27017
    volumes:
      - ./app:/app
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo:
